<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;
class StateTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        
	DB::table('states')->delete();
	$states = array(
		array('name' => "Andaman and Nicobar Islands",'country_id' => 101),
		array('name' => "Andhra Pradesh",'country_id' => 101),
		array('name' => "Arunachal Pradesh",'country_id' => 101),
		array('name' => "Assam",'country_id' => 101),
		array('name' => "Bihar",'country_id' => 101),
		array('name' => "Chandigarh",'country_id' => 101),
		array('name' => "Chhattisgarh",'country_id' => 101),
		array('name' => "Dadra and Nagar Haveli",'country_id' => 101),
		array('name' => "Daman and Diu",'country_id' => 101),
		array('name' => "Delhi",'country_id' => 101),
		array('name' => "Goa",'country_id' => 101),
		array('name' => "Gujarat",'country_id' => 101),
		array('name' => "Haryana",'country_id' => 101),
		array('name' => "Himachal Pradesh",'country_id' => 101),
		array('name' => "Jammu and Kashmir",'country_id' => 101),
		array('name' => "Jharkhand",'country_id' => 101),
		array('name' => "Karnataka",'country_id' => 101),
		array('name' => "Kenmore",'country_id' => 101),
		array('name' => "Kerala",'country_id' => 101),
		array('name' => "Lakshadweep",'country_id' => 101),
		array('name' => "Madhya Pradesh",'country_id' => 101),
		array('name' => "Maharashtra",'country_id' => 101),
		array('name' => "Manipur",'country_id' => 101),
		array('name' => "Meghalaya",'country_id' => 101),
		array('name' => "Mizoram",'country_id' => 101),
		array('name' => "Nagaland",'country_id' => 101),
		array('name' => "Narora",'country_id' => 101),
		array('name' => "Natwar",'country_id' => 101),
		array('name' => "Odisha",'country_id' => 101),
		array('name' => "Paschim Medinipur",'country_id' => 101),
		array('name' => "Pondicherry",'country_id' => 101),
		array('name' => "Punjab",'country_id' => 101),
		array('name' => "Rajasthan",'country_id' => 101),
		array('name' => "Sikkim",'country_id' => 101),
		array('name' => "Tamil Nadu",'country_id' => 101),
		array('name' => "Telangana",'country_id' => 101),
		array('name' => "Tripura",'country_id' => 101),
		array('name' => "Uttar Pradesh",'country_id' => 101),
		array('name' => "Uttarakhand",'country_id' => 101),
		array('name' => "Vaishali",'country_id' => 101),
		array('name' => "West Bengal",'country_id' => 101),
		array('name' => "Badakhshan",'country_id' => 1),
		array('name' => "Badgis",'country_id' => 1),
		array('name' => "Baglan",'country_id' => 1),
		array('name' => "Balkh",'country_id' => 1),
		array('name' => "Bamiyan",'country_id' => 1),
		array('name' => "Farah",'country_id' => 1),
		array('name' => "Faryab",'country_id' => 1),
		array('name' => "Gawr",'country_id' => 1),
		array('name' => "Gazni",'country_id' => 1),
		array('name' => "Herat",'country_id' => 1),
		array('name' => "Hilmand",'country_id' => 1),
		array('name' => "Jawzjan",'country_id' => 1),
		array('name' => "Kabul",'country_id' => 1),
		array('name' => "Kapisa",'country_id' => 1),
		array('name' => "Khawst",'country_id' => 1),
		array('name' => "Kunar",'country_id' => 1),
		array('name' => "Lagman",'country_id' => 1),
		array('name' => "Lawghar",'country_id' => 1),
		array('name' => "Nangarhar",'country_id' => 1),
		array('name' => "Nimruz",'country_id' => 1),
		array('name' => "Nuristan",'country_id' => 1),
		array('name' => "Paktika",'country_id' => 1),
		array('name' => "Paktiya",'country_id' => 1),
		array('name' => "Parwan",'country_id' => 1),
		array('name' => "Qandahar",'country_id' => 1),
		array('name' => "Qunduz",'country_id' => 1),
		array('name' => "Samangan",'country_id' => 1),
		array('name' => "Sar-e Pul",'country_id' => 1),
		array('name' => "Takhar",'country_id' => 1),
		array('name' => "Uruzgan",'country_id' => 1),
		array('name' => "Wardak",'country_id' => 1),
		array('name' => "Zabul",'country_id' => 1),
		array('name' => "Berat",'country_id' => 2),
		array('name' => "Bulqize",'country_id' => 2),
		array('name' => "Delvine",'country_id' => 2),
		array('name' => "Devoll",'country_id' => 2),
		array('name' => "Dibre",'country_id' => 2),
		array('name' => "Durres",'country_id' => 2),
		array('name' => "Elbasan",'country_id' => 2),
		array('name' => "Fier",'country_id' => 2),
		array('name' => "Gjirokaster",'country_id' => 2),
		array('name' => "Gramsh",'country_id' => 2),
		array('name' => "Has",'country_id' => 2),
		array('name' => "Kavaje",'country_id' => 2),
		array('name' => "Kolonje",'country_id' => 2),
		array('name' => "Korce",'country_id' => 2),
		array('name' => "Kruje",'country_id' => 2),
		array('name' => "Kucove",'country_id' => 2),
		array('name' => "Kukes",'country_id' => 2),
		array('name' => "Kurbin",'country_id' => 2),
		array('name' => "Lezhe",'country_id' => 2),
		array('name' => "Librazhd",'country_id' => 2),
		array('name' => "Lushnje",'country_id' => 2),
		array('name' => "Mallakaster",'country_id' => 2),
		array('name' => "Malsi e Madhe",'country_id' => 2),
		array('name' => "Mat",'country_id' => 2),
		array('name' => "Mirdite",'country_id' => 2),
		array('name' => "Peqin",'country_id' => 2),
		array('name' => "Permet",'country_id' => 2),
		array('name' => "Pogradec",'country_id' => 2),
		array('name' => "Puke",'country_id' => 2),
		array('name' => "Sarande",'country_id' => 2),
		array('name' => "Shkoder",'country_id' => 2),
		array('name' => "Skrapar",'country_id' => 2),
		array('name' => "Tepelene",'country_id' => 2),
		array('name' => "Tirane",'country_id' => 2),
		array('name' => "Tropoje",'country_id' => 2),
		array('name' => "Vlore",'country_id' => 2),
		array('name' => "'Ayn Daflah",'country_id' => 3),
		array('name' => "'Ayn Tamushanat",'country_id' => 3),
		array('name' => "Adrar",'country_id' => 3),
		array('name' => "Algiers",'country_id' => 3),
		array('name' => "Annabah",'country_id' => 3),
		array('name' => "Bashshar",'country_id' => 3),
		array('name' => "Batnah",'country_id' => 3),
		array('name' => "Bijayah",'country_id' => 3),
		array('name' => "Biskrah",'country_id' => 3),
		array('name' => "Blidah",'country_id' => 3),
		array('name' => "Buirah",'country_id' => 3),
		array('name' => "Bumardas",'country_id' => 3),
		array('name' => "Burj Bu Arririj",'country_id' => 3),
		array('name' => "Ghalizan",'country_id' => 3),
		array('name' => "Ghardayah",'country_id' => 3),
		array('name' => "Ilizi",'country_id' => 3),
		array('name' => "Jijili",'country_id' => 3),
		array('name' => "Jilfah",'country_id' => 3),
		array('name' => "Khanshalah",'country_id' => 3),
		array('name' => "Masilah",'country_id' => 3),
		array('name' => "Midyah",'country_id' => 3),
		array('name' => "Milah",'country_id' => 3),
		array('name' => "Muaskar",'country_id' => 3),
		array('name' => "Mustaghanam",'country_id' => 3),
		array('name' => "Naama",'country_id' => 3),
		array('name' => "Oran",'country_id' => 3),
		array('name' => "Ouargla",'country_id' => 3),
		array('name' => "Qalmah",'country_id' => 3),
		array('name' => "Qustantinah",'country_id' => 3),
		array('name' => "Sakikdah",'country_id' => 3),
		array('name' => "Satif",'country_id' => 3),
		array('name' => "Sayda'",'country_id' => 3),
		array('name' => "Sidi ban-al-'Abbas",'country_id' => 3),
		array('name' => "Suq Ahras",'country_id' => 3),
		array('name' => "Tamanghasat",'country_id' => 3),
		array('name' => "Tibazah",'country_id' => 3),
		array('name' => "Tibissah",'country_id' => 3),
		array('name' => "Tilimsan",'country_id' => 3),
		array('name' => "Tinduf",'country_id' => 3),
		array('name' => "Tisamsilt",'country_id' => 3),
		array('name' => "Tiyarat",'country_id' => 3),
		array('name' => "Tizi Wazu",'country_id' => 3),
		array('name' => "Umm-al-Bawaghi",'country_id' => 3),
		array('name' => "Wahran",'country_id' => 3),
		array('name' => "Warqla",'country_id' => 3),
		array('name' => "Wilaya d Alger",'country_id' => 3),
		array('name' => "Wilaya de Bejaia",'country_id' => 3),
		array('name' => "Wilaya de Constantine",'country_id' => 3),
		array('name' => "al-Aghwat",'country_id' => 3),
		array('name' => "al-Bayadh",'country_id' => 3),
		array('name' => "al-Jaza'ir",'country_id' => 3),
		array('name' => "al-Wad",'country_id' => 3),
		array('name' => "ash-Shalif",'country_id' => 3),
		array('name' => "at-Tarif",'country_id' => 3),
		array('name' => "Eastern",'country_id' => 4),
		array('name' => "Manu'a",'country_id' => 4),
		array('name' => "Swains Island",'country_id' => 4),
		array('name' => "Western",'country_id' => 4),
		array('name' => "Andorra la Vella",'country_id' => 5),
		array('name' => "Canillo",'country_id' => 5),
		array('name' => "Encamp",'country_id' => 5),
		array('name' => "La Massana",'country_id' => 5),
		array('name' => "Les Escaldes",'country_id' => 5),
		array('name' => "Ordino",'country_id' => 5),
		array('name' => "Sant Julia de Loria",'country_id' => 5),
		array('name' => "Bengo",'country_id' => 6),
		array('name' => "Benguela",'country_id' => 6),
		array('name' => "Bie",'country_id' => 6),
		array('name' => "Cabinda",'country_id' => 6),
		array('name' => "Cunene",'country_id' => 6),
		array('name' => "Huambo",'country_id' => 6),
		array('name' => "Huila",'country_id' => 6),
		array('name' => "Kuando-Kubango",'country_id' => 6),
		array('name' => "Kwanza Norte",'country_id' => 6),
		array('name' => "Kwanza Sul",'country_id' => 6),
		array('name' => "Luanda",'country_id' => 6),
		array('name' => "Lunda Norte",'country_id' => 6),
		array('name' => "Lunda Sul",'country_id' => 6),
		array('name' => "Malanje",'country_id' => 6),
		array('name' => "Moxico",'country_id' => 6),
		array('name' => "Namibe",'country_id' => 6),
		array('name' => "Uige",'country_id' => 6),
		array('name' => "Zaire",'country_id' => 6),
		array('name' => "Other Provinces",'country_id' => 7),
		array('name' => "Sector claimed by Argentina/Ch",'country_id' => 8),
		array('name' => "Sector claimed by Argentina/UK",'country_id' => 8),
		array('name' => "Sector claimed by Australia",'country_id' => 8),
		array('name' => "Sector claimed by France",'country_id' => 8),
		array('name' => "Sector claimed by New Zealand",'country_id' => 8),
		array('name' => "Sector claimed by Norway",'country_id' => 8),
		array('name' => "Unclaimed Sector",'country_id' => 8),
		array('name' => "Barbuda",'country_id' => 9),
		array('name' => "Saint George",'country_id' => 9),
		array('name' => "Saint John",'country_id' => 9),
		array('name' => "Saint Mary",'country_id' => 9),
		array('name' => "Saint Paul",'country_id' => 9),
		array('name' => "Saint Peter",'country_id' => 9),
		array('name' => "Saint Philip",'country_id' => 9),
		array('name' => "Buenos Aires",'country_id' => 10),
		array('name' => "Catamarca",'country_id' => 10),
		array('name' => "Chaco",'country_id' => 10),
		array('name' => "Chubut",'country_id' => 10),
		array('name' => "Cordoba",'country_id' => 10),
		array('name' => "Corrientes",'country_id' => 10),
		array('name' => "Distrito Federal",'country_id' => 10),
		array('name' => "Entre Rios",'country_id' => 10),
		array('name' => "Formosa",'country_id' => 10),
		array('name' => "Jujuy",'country_id' => 10),
		array('name' => "La Pampa",'country_id' => 10),
		array('name' => "La Rioja",'country_id' => 10),
		array('name' => "Mendoza",'country_id' => 10),
		array('name' => "Misiones",'country_id' => 10),
		array('name' => "Neuquen",'country_id' => 10),
		array('name' => "Rio Negro",'country_id' => 10),
		array('name' => "Salta",'country_id' => 10),
		array('name' => "San Juan",'country_id' => 10),
		array('name' => "San Luis",'country_id' => 10),
		array('name' => "Santa Cruz",'country_id' => 10),
		array('name' => "Santa Fe",'country_id' => 10),
		array('name' => "Santiago del Estero",'country_id' => 10),
		array('name' => "Tierra del Fuego",'country_id' => 10),
		array('name' => "Tucuman",'country_id' => 10),
		array('name' => "Aragatsotn",'country_id' => 11),
		array('name' => "Ararat",'country_id' => 11),
		array('name' => "Armavir",'country_id' => 11),
		array('name' => "Gegharkunik",'country_id' => 11),
		array('name' => "Kotaik",'country_id' => 11),
		array('name' => "Lori",'country_id' => 11),
		array('name' => "Shirak",'country_id' => 11),
		array('name' => "Stepanakert",'country_id' => 11),
		array('name' => "Syunik",'country_id' => 11),
		array('name' => "Tavush",'country_id' => 11),
		array('name' => "Vayots Dzor",'country_id' => 11),
		array('name' => "Yerevan",'country_id' => 11),
		array('name' => "Aruba",'country_id' => 12),
		array('name' => "Auckland",'country_id' => 13),
		array('name' => "Australian Capital Territory",'country_id' => 13),
		array('name' => "Balgowlah",'country_id' => 13),
		array('name' => "Balmain",'country_id' => 13),
		array('name' => "Bankstown",'country_id' => 13),
		array('name' => "Baulkham Hills",'country_id' => 13),
		array('name' => "Bonnet Bay",'country_id' => 13),
		array('name' => "Camberwell",'country_id' => 13),
		array('name' => "Carole Park",'country_id' => 13),
		array('name' => "Castle Hill",'country_id' => 13),
		array('name' => "Caulfield",'country_id' => 13),
		array('name' => "Chatswood",'country_id' => 13),
		array('name' => "Cheltenham",'country_id' => 13),
		array('name' => "Cherrybrook",'country_id' => 13),
		array('name' => "Clayton",'country_id' => 13),
		array('name' => "Collingwood",'country_id' => 13),
		array('name' => "Frenchs Forest",'country_id' => 13),
		array('name' => "Hawthorn",'country_id' => 13),
		array('name' => "Jannnali",'country_id' => 13),
		array('name' => "Knoxfield",'country_id' => 13),
		array('name' => "Melbourne",'country_id' => 13),
		array('name' => "New South Wales",'country_id' => 13),
		array('name' => "Northern Territory",'country_id' => 13),
		array('name' => "Perth",'country_id' => 13),
		array('name' => "Queensland",'country_id' => 13),
		array('name' => "South Australia",'country_id' => 13),
		array('name' => "Tasmania",'country_id' => 13),
		array('name' => "Templestowe",'country_id' => 13),
		array('name' => "Victoria",'country_id' => 13),
		array('name' => "Werribee south",'country_id' => 13),
		array('name' => "Western Australia",'country_id' => 13),
		array('name' => "Wheeler",'country_id' => 13),
		array('name' => "Bundesland Salzburg",'country_id' => 14),
		array('name' => "Bundesland Steiermark",'country_id' => 14),
		array('name' => "Bundesland Tirol",'country_id' => 14),
		array('name' => "Burgenland",'country_id' => 14),
		array('name' => "Carinthia",'country_id' => 14),
		array('name' => "Karnten",'country_id' => 14),
		array('name' => "Liezen",'country_id' => 14),
		array('name' => "Lower Austria",'country_id' => 14),
		array('name' => "Niederosterreich",'country_id' => 14),
		array('name' => "Oberosterreich",'country_id' => 14),
		array('name' => "Salzburg",'country_id' => 14),
		array('name' => "Schleswig-Holstein",'country_id' => 14),
		array('name' => "Steiermark",'country_id' => 14),
		array('name' => "Styria",'country_id' => 14),
		array('name' => "Tirol",'country_id' => 14),
		array('name' => "Upper Austria",'country_id' => 14),
		array('name' => "Vorarlberg",'country_id' => 14),
		array('name' => "Wien",'country_id' => 14),
		array('name' => "Abseron",'country_id' => 15),
		array('name' => "Baki Sahari",'country_id' => 15),
		array('name' => "Ganca",'country_id' => 15),
		array('name' => "Ganja",'country_id' => 15),
		array('name' => "Kalbacar",'country_id' => 15),
		array('name' => "Lankaran",'country_id' => 15),
		array('name' => "Mil-Qarabax",'country_id' => 15),
		array('name' => "Mugan-Salyan",'country_id' => 15),
		array('name' => "Nagorni-Qarabax",'country_id' => 15),
		array('name' => "Naxcivan",'country_id' => 15),
		array('name' => "Priaraks",'country_id' => 15),
		array('name' => "Qazax",'country_id' => 15),
		array('name' => "Saki",'country_id' => 15),
		array('name' => "Sirvan",'country_id' => 15),
		array('name' => "Xacmaz",'country_id' => 15),
		array('name' => "Abaco",'country_id' => 16),
		array('name' => "Acklins Island",'country_id' => 16),
		array('name' => "Andros",'country_id' => 16),
		array('name' => "Berry Islands",'country_id' => 16),
		array('name' => "Biminis",'country_id' => 16),
		array('name' => "Cat Island",'country_id' => 16),
		array('name' => "Crooked Island",'country_id' => 16),
		array('name' => "Eleuthera",'country_id' => 16),
		array('name' => "Exuma and Cays",'country_id' => 16),
		array('name' => "Grand Bahama",'country_id' => 16),
		array('name' => "Inagua Islands",'country_id' => 16),
		array('name' => "Long Island",'country_id' => 16),
		array('name' => "Mayaguana",'country_id' => 16),
		array('name' => "New Providence",'country_id' => 16),
		array('name' => "Ragged Island",'country_id' => 16),
		array('name' => "Rum Cay",'country_id' => 16),
		array('name' => "San Salvador",'country_id' => 16),
		array('name' => "'Isa",'country_id' => 17),
		array('name' => "Badiyah",'country_id' => 17),
		array('name' => "Hidd",'country_id' => 17),
		array('name' => "Jidd Hafs",'country_id' => 17),
		array('name' => "Mahama",'country_id' => 17),
		array('name' => "Manama",'country_id' => 17),
		array('name' => "Sitrah",'country_id' => 17),
		array('name' => "al-Manamah",'country_id' => 17),
		array('name' => "al-Muharraq",'country_id' => 17),
		array('name' => "ar-Rifa'a",'country_id' => 17),
		array('name' => "Bagar Hat",'country_id' => 18),
		array('name' => "Bandarban",'country_id' => 18),
		array('name' => "Barguna",'country_id' => 18),
		array('name' => "Barisal",'country_id' => 18),
		array('name' => "Bhola",'country_id' => 18),
		array('name' => "Bogora",'country_id' => 18),
		array('name' => "Brahman Bariya",'country_id' => 18),
		array('name' => "Chandpur",'country_id' => 18),
		array('name' => "Chattagam",'country_id' => 18),
		array('name' => "Chittagong Division",'country_id' => 18),
		array('name' => "Chuadanga",'country_id' => 18),
		array('name' => "Dhaka",'country_id' => 18),
		array('name' => "Dinajpur",'country_id' => 18),
		array('name' => "Faridpur",'country_id' => 18),
		array('name' => "Feni",'country_id' => 18),
		array('name' => "Gaybanda",'country_id' => 18),
		array('name' => "Gazipur",'country_id' => 18),
		array('name' => "Gopalganj",'country_id' => 18),
		array('name' => "Habiganj",'country_id' => 18),
		array('name' => "Jaipur Hat",'country_id' => 18),
		array('name' => "Jamalpur",'country_id' => 18),
		array('name' => "Jessor",'country_id' => 18),
		array('name' => "Jhalakati",'country_id' => 18),
		array('name' => "Jhanaydah",'country_id' => 18),
		array('name' => "Khagrachhari",'country_id' => 18),
		array('name' => "Khulna",'country_id' => 18),
		array('name' => "Kishorganj",'country_id' => 18),
		array('name' => "Koks Bazar",'country_id' => 18),
		array('name' => "Komilla",'country_id' => 18),
		array('name' => "Kurigram",'country_id' => 18),
		array('name' => "Kushtiya",'country_id' => 18),
		array('name' => "Lakshmipur",'country_id' => 18),
		array('name' => "Lalmanir Hat",'country_id' => 18),
		array('name' => "Madaripur",'country_id' => 18),
		array('name' => "Magura",'country_id' => 18),
		array('name' => "Maimansingh",'country_id' => 18),
		array('name' => "Manikganj",'country_id' => 18),
		array('name' => "Maulvi Bazar",'country_id' => 18),
		array('name' => "Meherpur",'country_id' => 18),
		array('name' => "Munshiganj",'country_id' => 18),
		array('name' => "Naral",'country_id' => 18),
		array('name' => "Narayanganj",'country_id' => 18),
		array('name' => "Narsingdi",'country_id' => 18),
		array('name' => "Nator",'country_id' => 18),
		array('name' => "Naugaon",'country_id' => 18),
		array('name' => "Nawabganj",'country_id' => 18),
		array('name' => "Netrakona",'country_id' => 18),
		array('name' => "Nilphamari",'country_id' => 18),
		array('name' => "Noakhali",'country_id' => 18),
		array('name' => "Pabna",'country_id' => 18),
		array('name' => "Panchagarh",'country_id' => 18),
		array('name' => "Patuakhali",'country_id' => 18),
		array('name' => "Pirojpur",'country_id' => 18),
		array('name' => "Rajbari",'country_id' => 18),
		array('name' => "Rajshahi",'country_id' => 18),
		array('name' => "Rangamati",'country_id' => 18),
		array('name' => "Rangpur",'country_id' => 18),
		array('name' => "Satkhira",'country_id' => 18),
		array('name' => "Shariatpur",'country_id' => 18),
		array('name' => "Sherpur",'country_id' => 18),
		array('name' => "Silhat",'country_id' => 18),
		array('name' => "Sirajganj",'country_id' => 18),
		array('name' => "Sunamganj",'country_id' => 18),
		array('name' => "Tangayal",'country_id' => 18),
		array('name' => "Thakurgaon",'country_id' => 18),
		array('name' => "Christ Church",'country_id' => 19),
		array('name' => "Saint Andrew",'country_id' => 19),
		array('name' => "Saint George",'country_id' => 19),
		array('name' => "Saint James",'country_id' => 19),
		array('name' => "Saint John",'country_id' => 19),
		array('name' => "Saint Joseph",'country_id' => 19),
		array('name' => "Saint Lucy",'country_id' => 19),
		array('name' => "Saint Michael",'country_id' => 19),
		array('name' => "Saint Peter",'country_id' => 19),
		array('name' => "Saint Philip",'country_id' => 19),
		array('name' => "Saint Thomas",'country_id' => 19),
		array('name' => "Brest",'country_id' => 20),
		array('name' => "Homjel'",'country_id' => 20),
		array('name' => "Hrodna",'country_id' => 20),
		array('name' => "Mahiljow",'country_id' => 20),
		array('name' => "Mahilyowskaya Voblasts",'country_id' => 20),
		array('name' => "Minsk",'country_id' => 20),
		array('name' => "Minskaja Voblasts'",'country_id' => 20),
		array('name' => "Petrik",'country_id' => 20),
		array('name' => "Vicebsk",'country_id' => 20),
		array('name' => "Antwerpen",'country_id' => 21),
		array('name' => "Berchem",'country_id' => 21),
		array('name' => "Brabant",'country_id' => 21),
		array('name' => "Brabant Wallon",'country_id' => 21),
		array('name' => "Brussel",'country_id' => 21),
		array('name' => "East Flanders",'country_id' => 21),
		array('name' => "Hainaut",'country_id' => 21),
		array('name' => "Liege",'country_id' => 21),
		array('name' => "Limburg",'country_id' => 21),
		array('name' => "Luxembourg",'country_id' => 21),
		array('name' => "Namur",'country_id' => 21),
		array('name' => "Ontario",'country_id' => 21),
		array('name' => "Oost-Vlaanderen",'country_id' => 21),
		array('name' => "Provincie Brabant",'country_id' => 21),
		array('name' => "Vlaams-Brabant",'country_id' => 21),
		array('name' => "Wallonne",'country_id' => 21),
		array('name' => "West-Vlaanderen",'country_id' => 21),
		array('name' => "Belize",'country_id' => 22),
		array('name' => "Cayo",'country_id' => 22),
		array('name' => "Corozal",'country_id' => 22),
		array('name' => "Orange Walk",'country_id' => 22),
		array('name' => "Stann Creek",'country_id' => 22),
		array('name' => "Toledo",'country_id' => 22),
		array('name' => "Alibori",'country_id' => 23),
		array('name' => "Atacora",'country_id' => 23),
		array('name' => "Atlantique",'country_id' => 23),
		array('name' => "Borgou",'country_id' => 23),
		array('name' => "Collines",'country_id' => 23),
		array('name' => "Couffo",'country_id' => 23),
		array('name' => "Donga",'country_id' => 23),
		array('name' => "Littoral",'country_id' => 23),
		array('name' => "Mono",'country_id' => 23),
		array('name' => "Oueme",'country_id' => 23),
		array('name' => "Plateau",'country_id' => 23),
		array('name' => "Zou",'country_id' => 23),
		array('name' => "Hamilton",'country_id' => 24),
		array('name' => "Saint George",'country_id' => 24),
		array('name' => "Bumthang",'country_id' => 25),
		array('name' => "Chhukha",'country_id' => 25),
		array('name' => "Chirang",'country_id' => 25),
		array('name' => "Daga",'country_id' => 25),
		array('name' => "Geylegphug",'country_id' => 25),
		array('name' => "Ha",'country_id' => 25),
		array('name' => "Lhuntshi",'country_id' => 25),
		array('name' => "Mongar",'country_id' => 25),
		array('name' => "Pemagatsel",'country_id' => 25),
		array('name' => "Punakha",'country_id' => 25),
		array('name' => "Rinpung",'country_id' => 25),
		array('name' => "Samchi",'country_id' => 25),
		array('name' => "Samdrup Jongkhar",'country_id' => 25),
		array('name' => "Shemgang",'country_id' => 25),
		array('name' => "Tashigang",'country_id' => 25),
		array('name' => "Timphu",'country_id' => 25),
		array('name' => "Tongsa",'country_id' => 25),
		array('name' => "Wangdiphodrang",'country_id' => 25),
		array('name' => "Beni",'country_id' => 26),
		array('name' => "Chuquisaca",'country_id' => 26),
		array('name' => "Cochabamba",'country_id' => 26),
		array('name' => "La Paz",'country_id' => 26),
		array('name' => "Oruro",'country_id' => 26),
		array('name' => "Pando",'country_id' => 26),
		array('name' => "Potosi",'country_id' => 26),
		array('name' => "Santa Cruz",'country_id' => 26),
		array('name' => "Tarija",'country_id' => 26),
		array('name' => "Federacija Bosna i Hercegovina",'country_id' => 27),
		array('name' => "Republika Srpska",'country_id' => 27),
		array('name' => "Central Bobonong",'country_id' => 28),
		array('name' => "Central Boteti",'country_id' => 28),
		array('name' => "Central Mahalapye",'country_id' => 28),
		array('name' => "Central Serowe-Palapye",'country_id' => 28),
		array('name' => "Central Tutume",'country_id' => 28),
		array('name' => "Chobe",'country_id' => 28),
		array('name' => "Francistown",'country_id' => 28),
		array('name' => "Gaborone",'country_id' => 28),
		array('name' => "Ghanzi",'country_id' => 28),
		array('name' => "Jwaneng",'country_id' => 28),
		array('name' => "Kgalagadi North",'country_id' => 28),
		array('name' => "Kgalagadi South",'country_id' => 28),
		array('name' => "Kgatleng",'country_id' => 28),
		array('name' => "Kweneng",'country_id' => 28),
		array('name' => "Lobatse",'country_id' => 28),
		array('name' => "Ngamiland",'country_id' => 28),
		array('name' => "Ngwaketse",'country_id' => 28),
		array('name' => "North East",'country_id' => 28),
		array('name' => "Okavango",'country_id' => 28),
		array('name' => "Orapa",'country_id' => 28),
		array('name' => "Selibe Phikwe",'country_id' => 28),
		array('name' => "South East",'country_id' => 28),
		array('name' => "Sowa",'country_id' => 28),
		array('name' => "Bouvet Island",'country_id' => 29),
		array('name' => "Acre",'country_id' => 30),
		array('name' => "Alagoas",'country_id' => 30),
		array('name' => "Amapa",'country_id' => 30),
		array('name' => "Amazonas",'country_id' => 30),
		array('name' => "Bahia",'country_id' => 30),
		array('name' => "Ceara",'country_id' => 30),
		array('name' => "Distrito Federal",'country_id' => 30),
		array('name' => "Espirito Santo",'country_id' => 30),
		array('name' => "Estado de Sao Paulo",'country_id' => 30),
		array('name' => "Goias",'country_id' => 30),
		array('name' => "Maranhao",'country_id' => 30),
		array('name' => "Mato Grosso",'country_id' => 30),
		array('name' => "Mato Grosso do Sul",'country_id' => 30),
		array('name' => "Minas Gerais",'country_id' => 30),
		array('name' => "Para",'country_id' => 30),
		array('name' => "Paraiba",'country_id' => 30),
		array('name' => "Parana",'country_id' => 30),
		array('name' => "Pernambuco",'country_id' => 30),
		array('name' => "Piaui",'country_id' => 30),
		array('name' => "Rio Grande do Norte",'country_id' => 30),
		array('name' => "Rio Grande do Sul",'country_id' => 30),
		array('name' => "Rio de Janeiro",'country_id' => 30),
		array('name' => "Rondonia",'country_id' => 30),
		array('name' => "Roraima",'country_id' => 30),
		array('name' => "Santa Catarina",'country_id' => 30),
		array('name' => "Sao Paulo",'country_id' => 30),
		array('name' => "Sergipe",'country_id' => 30),
		array('name' => "Tocantins",'country_id' => 30),
		array('name' => "British Indian Ocean Territory",'country_id' => 31),
		array('name' => "Belait",'country_id' => 32),
		array('name' => "Brunei-Muara",'country_id' => 32),
		array('name' => "Temburong",'country_id' => 32),
		array('name' => "Tutong",'country_id' => 32),
		array('name' => "Blagoevgrad",'country_id' => 33),
		array('name' => "Burgas",'country_id' => 33),
		array('name' => "Dobrich",'country_id' => 33),
		array('name' => "Gabrovo",'country_id' => 33),
		array('name' => "Haskovo",'country_id' => 33),
		array('name' => "Jambol",'country_id' => 33),
		array('name' => "Kardzhali",'country_id' => 33),
		array('name' => "Kjustendil",'country_id' => 33),
		array('name' => "Lovech",'country_id' => 33),
		array('name' => "Montana",'country_id' => 33),
		array('name' => "Oblast Sofiya-Grad",'country_id' => 33),
		array('name' => "Pazardzhik",'country_id' => 33),
		array('name' => "Pernik",'country_id' => 33),
		array('name' => "Pleven",'country_id' => 33),
		array('name' => "Plovdiv",'country_id' => 33),
		array('name' => "Razgrad",'country_id' => 33),
		array('name' => "Ruse",'country_id' => 33),
		array('name' => "Shumen",'country_id' => 33),
		array('name' => "Silistra",'country_id' => 33),
		array('name' => "Sliven",'country_id' => 33),
		array('name' => "Smoljan",'country_id' => 33),
		array('name' => "Sofija grad",'country_id' => 33),
		array('name' => "Sofijska oblast",'country_id' => 33),
		array('name' => "Stara Zagora",'country_id' => 33),
		array('name' => "Targovishte",'country_id' => 33),
		array('name' => "Varna",'country_id' => 33),
		array('name' => "Veliko Tarnovo",'country_id' => 33),
		array('name' => "Vidin",'country_id' => 33),
		array('name' => "Vraca",'country_id' => 33),
		array('name' => "Yablaniza",'country_id' => 33),
		array('name' => "Bale",'country_id' => 34),
		array('name' => "Bam",'country_id' => 34),
		array('name' => "Bazega",'country_id' => 34),
		array('name' => "Bougouriba",'country_id' => 34),
		array('name' => "Boulgou",'country_id' => 34),
		array('name' => "Boulkiemde",'country_id' => 34),
		array('name' => "Comoe",'country_id' => 34),
		array('name' => "Ganzourgou",'country_id' => 34),
		array('name' => "Gnagna",'country_id' => 34),
		array('name' => "Gourma",'country_id' => 34),
		array('name' => "Houet",'country_id' => 34),
		array('name' => "Ioba",'country_id' => 34),
		array('name' => "Kadiogo",'country_id' => 34),
		array('name' => "Kenedougou",'country_id' => 34),
		array('name' => "Komandjari",'country_id' => 34),
		array('name' => "Kompienga",'country_id' => 34),
		array('name' => "Kossi",'country_id' => 34),
		array('name' => "Kouritenga",'country_id' => 34),
		array('name' => "Kourweogo",'country_id' => 34),
		array('name' => "Leraba",'country_id' => 34),
		array('name' => "Mouhoun",'country_id' => 34),
		array('name' => "Nahouri",'country_id' => 34),
		array('name' => "Namentenga",'country_id' => 34),
		array('name' => "Noumbiel",'country_id' => 34),
		array('name' => "Oubritenga",'country_id' => 34),
		array('name' => "Oudalan",'country_id' => 34),
		array('name' => "Passore",'country_id' => 34),
		array('name' => "Poni",'country_id' => 34),
		array('name' => "Sanguie",'country_id' => 34),
		array('name' => "Sanmatenga",'country_id' => 34),
		array('name' => "Seno",'country_id' => 34),
		array('name' => "Sissili",'country_id' => 34),
		array('name' => "Soum",'country_id' => 34),
		array('name' => "Sourou",'country_id' => 34),
		array('name' => "Tapoa",'country_id' => 34),
		array('name' => "Tuy",'country_id' => 34),
		array('name' => "Yatenga",'country_id' => 34),
		array('name' => "Zondoma",'country_id' => 34),
		array('name' => "Zoundweogo",'country_id' => 34),
		array('name' => "Bubanza",'country_id' => 35),
		array('name' => "Bujumbura",'country_id' => 35),
		array('name' => "Bururi",'country_id' => 35),
		array('name' => "Cankuzo",'country_id' => 35),
		array('name' => "Cibitoke",'country_id' => 35),
		array('name' => "Gitega",'country_id' => 35),
		array('name' => "Karuzi",'country_id' => 35),
		array('name' => "Kayanza",'country_id' => 35),
		array('name' => "Kirundo",'country_id' => 35),
		array('name' => "Makamba",'country_id' => 35),
		array('name' => "Muramvya",'country_id' => 35),
		array('name' => "Muyinga",'country_id' => 35),
		array('name' => "Ngozi",'country_id' => 35),
		array('name' => "Rutana",'country_id' => 35),
		array('name' => "Ruyigi",'country_id' => 35),
		array('name' => "Banteay Mean Chey",'country_id' => 36),
		array('name' => "Bat Dambang",'country_id' => 36),
		array('name' => "Kampong Cham",'country_id' => 36),
		array('name' => "Kampong Chhnang",'country_id' => 36),
		array('name' => "Kampong Spoeu",'country_id' => 36),
		array('name' => "Kampong Thum",'country_id' => 36),
		array('name' => "Kampot",'country_id' => 36),
		array('name' => "Kandal",'country_id' => 36),
		array('name' => "Kaoh Kong",'country_id' => 36),
		array('name' => "Kracheh",'country_id' => 36),
		array('name' => "Krong Kaeb",'country_id' => 36),
		array('name' => "Krong Pailin",'country_id' => 36),
		array('name' => "Krong Preah Sihanouk",'country_id' => 36),
		array('name' => "Mondol Kiri",'country_id' => 36),
		array('name' => "Otdar Mean Chey",'country_id' => 36),
		array('name' => "Phnum Penh",'country_id' => 36),
		array('name' => "Pousat",'country_id' => 36),
		array('name' => "Preah Vihear",'country_id' => 36),
		array('name' => "Prey Veaeng",'country_id' => 36),
		array('name' => "Rotanak Kiri",'country_id' => 36),
		array('name' => "Siem Reab",'country_id' => 36),
		array('name' => "Stueng Traeng",'country_id' => 36),
		array('name' => "Svay Rieng",'country_id' => 36),
		array('name' => "Takaev",'country_id' => 36),
		array('name' => "Adamaoua",'country_id' => 37),
		array('name' => "Centre",'country_id' => 37),
		array('name' => "Est",'country_id' => 37),
		array('name' => "Littoral",'country_id' => 37),
		array('name' => "Nord",'country_id' => 37),
		array('name' => "Nord Extreme",'country_id' => 37),
		array('name' => "Nordouest",'country_id' => 37),
		array('name' => "Ouest",'country_id' => 37),
		array('name' => "Sud",'country_id' => 37),
		array('name' => "Sudouest",'country_id' => 37),
		array('name' => "Alberta",'country_id' => 38),
		array('name' => "British Columbia",'country_id' => 38),
		array('name' => "Manitoba",'country_id' => 38),
		array('name' => "New Brunswick",'country_id' => 38),
		array('name' => "Newfoundland and Labrador",'country_id' => 38),
		array('name' => "Northwest Territories",'country_id' => 38),
		array('name' => "Nova Scotia",'country_id' => 38),
		array('name' => "Nunavut",'country_id' => 38),
		array('name' => "Ontario",'country_id' => 38),
		array('name' => "Prince Edward Island",'country_id' => 38),
		array('name' => "Quebec",'country_id' => 38),
		array('name' => "Saskatchewan",'country_id' => 38),
		array('name' => "Yukon",'country_id' => 38),
		array('name' => "Boavista",'country_id' => 39),
		array('name' => "Brava",'country_id' => 39),
		array('name' => "Fogo",'country_id' => 39),
		array('name' => "Maio",'country_id' => 39),
		array('name' => "Sal",'country_id' => 39),
		array('name' => "Santo Antao",'country_id' => 39),
		array('name' => "Sao Nicolau",'country_id' => 39),
		array('name' => "Sao Tiago",'country_id' => 39),
		array('name' => "Sao Vicente",'country_id' => 39),
		array('name' => "Grand Cayman",'country_id' => 40),
		array('name' => "Bamingui-Bangoran",'country_id' => 41),
		array('name' => "Bangui",'country_id' => 41),
		array('name' => "Basse-Kotto",'country_id' => 41),
		array('name' => "Haut-Mbomou",'country_id' => 41),
		array('name' => "Haute-Kotto",'country_id' => 41),
		array('name' => "Kemo",'country_id' => 41),
		array('name' => "Lobaye",'country_id' => 41),
		array('name' => "Mambere-Kadei",'country_id' => 41),
		array('name' => "Mbomou",'country_id' => 41),
		array('name' => "Nana-Gribizi",'country_id' => 41),
		array('name' => "Nana-Mambere",'country_id' => 41),
		array('name' => "Ombella Mpoko",'country_id' => 41),
		array('name' => "Ouaka",'country_id' => 41),
		array('name' => "Ouham",'country_id' => 41),
		array('name' => "Ouham-Pende",'country_id' => 41),
		array('name' => "Sangha-Mbaere",'country_id' => 41),
		array('name' => "Vakaga",'country_id' => 41),
		array('name' => "Batha",'country_id' => 42),
		array('name' => "Biltine",'country_id' => 42),
		array('name' => "Bourkou-Ennedi-Tibesti",'country_id' => 42),
		array('name' => "Chari-Baguirmi",'country_id' => 42),
		array('name' => "Guera",'country_id' => 42),
		array('name' => "Kanem",'country_id' => 42),
		array('name' => "Lac",'country_id' => 42),
		array('name' => "Logone Occidental",'country_id' => 42),
		array('name' => "Logone Oriental",'country_id' => 42),
		array('name' => "Mayo-Kebbi",'country_id' => 42),
		array('name' => "Moyen-Chari",'country_id' => 42),
		array('name' => "Ouaddai",'country_id' => 42),
		array('name' => "Salamat",'country_id' => 42),
		array('name' => "Tandjile",'country_id' => 42),
		array('name' => "Aisen",'country_id' => 43),
		array('name' => "Antofagasta",'country_id' => 43),
		array('name' => "Araucania",'country_id' => 43),
		array('name' => "Atacama",'country_id' => 43),
		array('name' => "Bio Bio",'country_id' => 43),
		array('name' => "Coquimbo",'country_id' => 43),
		array('name' => "Libertador General Bernardo O'",'country_id' => 43),
		array('name' => "Los Lagos",'country_id' => 43),
		array('name' => "Magellanes",'country_id' => 43),
		array('name' => "Maule",'country_id' => 43),
		array('name' => "Metropolitana",'country_id' => 43),
		array('name' => "Metropolitana de Santiago",'country_id' => 43),
		array('name' => "Tarapaca",'country_id' => 43),
		array('name' => "Valparaiso",'country_id' => 43),
		array('name' => "Anhui",'country_id' => 44),
		array('name' => "Anhui Province",'country_id' => 44),
		array('name' => "Anhui Sheng",'country_id' => 44),
		array('name' => "Aomen",'country_id' => 44),
		array('name' => "Beijing",'country_id' => 44),
		array('name' => "Beijing Shi",'country_id' => 44),
		array('name' => "Chongqing",'country_id' => 44),
		array('name' => "Fujian",'country_id' => 44),
		array('name' => "Fujian Sheng",'country_id' => 44),
		array('name' => "Gansu",'country_id' => 44),
		array('name' => "Guangdong",'country_id' => 44),
		array('name' => "Guangdong Sheng",'country_id' => 44),
		array('name' => "Guangxi",'country_id' => 44),
		array('name' => "Guizhou",'country_id' => 44),
		array('name' => "Hainan",'country_id' => 44),
		array('name' => "Hebei",'country_id' => 44),
		array('name' => "Heilongjiang",'country_id' => 44),
		array('name' => "Henan",'country_id' => 44),
		array('name' => "Hubei",'country_id' => 44),
		array('name' => "Hunan",'country_id' => 44),
		array('name' => "Jiangsu",'country_id' => 44),
		array('name' => "Jiangsu Sheng",'country_id' => 44),
		array('name' => "Jiangxi",'country_id' => 44),
		array('name' => "Jilin",'country_id' => 44),
		array('name' => "Liaoning",'country_id' => 44),
		array('name' => "Liaoning Sheng",'country_id' => 44),
		array('name' => "Nei Monggol",'country_id' => 44),
		array('name' => "Ningxia Hui",'country_id' => 44),
		array('name' => "Qinghai",'country_id' => 44),
		array('name' => "Shaanxi",'country_id' => 44),
		array('name' => "Shandong",'country_id' => 44),
		array('name' => "Shandong Sheng",'country_id' => 44),
		array('name' => "Shanghai",'country_id' => 44),
		array('name' => "Shanxi",'country_id' => 44),
		array('name' => "Sichuan",'country_id' => 44),
		array('name' => "Tianjin",'country_id' => 44),
		array('name' => "Xianggang",'country_id' => 44),
		array('name' => "Xinjiang",'country_id' => 44),
		array('name' => "Xizang",'country_id' => 44),
		array('name' => "Yunnan",'country_id' => 44),
		array('name' => "Zhejiang",'country_id' => 44),
		array('name' => "Zhejiang Sheng",'country_id' => 44),
		array('name' => "Christmas Island",'country_id' => 45),
		array('name' => "Cocos (Keeling) Islands",'country_id' => 46),
		array('name' => "Amazonas",'country_id' => 47),
		array('name' => "Antioquia",'country_id' => 47),
		array('name' => "Arauca",'country_id' => 47),
		array('name' => "Atlantico",'country_id' => 47),
		array('name' => "Bogota",'country_id' => 47),
		array('name' => "Bolivar",'country_id' => 47),
		array('name' => "Boyaca",'country_id' => 47),
		array('name' => "Caldas",'country_id' => 47),
		array('name' => "Caqueta",'country_id' => 47),
		array('name' => "Casanare",'country_id' => 47),
		array('name' => "Cauca",'country_id' => 47),
		array('name' => "Cesar",'country_id' => 47),
		array('name' => "Choco",'country_id' => 47),
		array('name' => "Cordoba",'country_id' => 47),
		array('name' => "Cundinamarca",'country_id' => 47),
		array('name' => "Guainia",'country_id' => 47),
		array('name' => "Guaviare",'country_id' => 47),
		array('name' => "Huila",'country_id' => 47),
		array('name' => "La Guajira",'country_id' => 47),
		array('name' => "Magdalena",'country_id' => 47),
		array('name' => "Meta",'country_id' => 47),
		array('name' => "Narino",'country_id' => 47),
		array('name' => "Norte de Santander",'country_id' => 47),
		array('name' => "Putumayo",'country_id' => 47),
		array('name' => "Quindio",'country_id' => 47),
		array('name' => "Risaralda",'country_id' => 47),
		array('name' => "San Andres y Providencia",'country_id' => 47),
		array('name' => "Santander",'country_id' => 47),
		array('name' => "Sucre",'country_id' => 47),
		array('name' => "Tolima",'country_id' => 47),
		array('name' => "Valle del Cauca",'country_id' => 47),
		array('name' => "Vaupes",'country_id' => 47),
		array('name' => "Vichada",'country_id' => 47),
		array('name' => "Mwali",'country_id' => 48),
		array('name' => "Njazidja",'country_id' => 48),
		array('name' => "Nzwani",'country_id' => 48),
		array('name' => "Bouenza",'country_id' => 49),
		array('name' => "Brazzaville",'country_id' => 49),
		array('name' => "Cuvette",'country_id' => 49),
		array('name' => "Kouilou",'country_id' => 49),
		array('name' => "Lekoumou",'country_id' => 49),
		array('name' => "Likouala",'country_id' => 49),
		array('name' => "Niari",'country_id' => 49),
		array('name' => "Plateaux",'country_id' => 49),
		array('name' => "Pool",'country_id' => 49),
		array('name' => "Sangha",'country_id' => 49),
		array('name' => "Bandundu",'country_id' => 50),
		array('name' => "Bas-Congo",'country_id' => 50),
		array('name' => "Equateur",'country_id' => 50),
		array('name' => "Haut-Congo",'country_id' => 50),
		array('name' => "Kasai-Occidental",'country_id' => 50),
		array('name' => "Kasai-Oriental",'country_id' => 50),
		array('name' => "Katanga",'country_id' => 50),
		array('name' => "Kinshasa",'country_id' => 50),
		array('name' => "Maniema",'country_id' => 50),
		array('name' => "Nord-Kivu",'country_id' => 50),
		array('name' => "Sud-Kivu",'country_id' => 50),
		array('name' => "Aitutaki",'country_id' => 51),
		array('name' => "Atiu",'country_id' => 51),
		array('name' => "Mangaia",'country_id' => 51),
		array('name' => "Manihiki",'country_id' => 51),
		array('name' => "Mauke",'country_id' => 51),
		array('name' => "Mitiaro",'country_id' => 51),
		array('name' => "Nassau",'country_id' => 51),
		array('name' => "Pukapuka",'country_id' => 51),
		array('name' => "Rakahanga",'country_id' => 51),
		array('name' => "Rarotonga",'country_id' => 51),
		array('name' => "Tongareva",'country_id' => 51),
		array('name' => "Alajuela",'country_id' => 52),
		array('name' => "Cartago",'country_id' => 52),
		array('name' => "Guanacaste",'country_id' => 52),
		array('name' => "Heredia",'country_id' => 52),
		array('name' => "Limon",'country_id' => 52),
		array('name' => "Puntarenas",'country_id' => 52),
		array('name' => "San Jose",'country_id' => 52),
		array('name' => "Abidjan",'country_id' => 53),
		array('name' => "Agneby",'country_id' => 53),
		array('name' => "Bafing",'country_id' => 53),
		array('name' => "Denguele",'country_id' => 53),
		array('name' => "Dix-huit Montagnes",'country_id' => 53),
		array('name' => "Fromager",'country_id' => 53),
		array('name' => "Haut-Sassandra",'country_id' => 53),
		array('name' => "Lacs",'country_id' => 53),
		array('name' => "Lagunes",'country_id' => 53),
		array('name' => "Marahoue",'country_id' => 53),
		array('name' => "Moyen-Cavally",'country_id' => 53),
		array('name' => "Moyen-Comoe",'country_id' => 53),
		array('name' => "N'zi-Comoe",'country_id' => 53),
		array('name' => "Sassandra",'country_id' => 53),
		array('name' => "Savanes",'country_id' => 53),
		array('name' => "Sud-Bandama",'country_id' => 53),
		array('name' => "Sud-Comoe",'country_id' => 53),
		array('name' => "Vallee du Bandama",'country_id' => 53),
		array('name' => "Worodougou",'country_id' => 53),
		array('name' => "Zanzan",'country_id' => 53),
		array('name' => "Bjelovar-Bilogora",'country_id' => 54),
		array('name' => "Dubrovnik-Neretva",'country_id' => 54),
		array('name' => "Grad Zagreb",'country_id' => 54),
		array('name' => "Istra",'country_id' => 54),
		array('name' => "Karlovac",'country_id' => 54),
		array('name' => "Koprivnica-Krizhevci",'country_id' => 54),
		array('name' => "Krapina-Zagorje",'country_id' => 54),
		array('name' => "Lika-Senj",'country_id' => 54),
		array('name' => "Medhimurje",'country_id' => 54),
		array('name' => "Medimurska Zupanija",'country_id' => 54),
		array('name' => "Osijek-Baranja",'country_id' => 54),
		array('name' => "Osjecko-Baranjska Zupanija",'country_id' => 54),
		array('name' => "Pozhega-Slavonija",'country_id' => 54),
		array('name' => "Primorje-Gorski Kotar",'country_id' => 54),
		array('name' => "Shibenik-Knin",'country_id' => 54),
		array('name' => "Sisak-Moslavina",'country_id' => 54),
		array('name' => "Slavonski Brod-Posavina",'country_id' => 54),
		array('name' => "Split-Dalmacija",'country_id' => 54),
		array('name' => "Varazhdin",'country_id' => 54),
		array('name' => "Virovitica-Podravina",'country_id' => 54),
		array('name' => "Vukovar-Srijem",'country_id' => 54),
		array('name' => "Zadar",'country_id' => 54),
		array('name' => "Zagreb",'country_id' => 54),
		array('name' => "Camaguey",'country_id' => 55),
		array('name' => "Ciego de Avila",'country_id' => 55),
		array('name' => "Cienfuegos",'country_id' => 55),
		array('name' => "Ciudad de la Habana",'country_id' => 55),
		array('name' => "Granma",'country_id' => 55),
		array('name' => "Guantanamo",'country_id' => 55),
		array('name' => "Habana",'country_id' => 55),
		array('name' => "Holguin",'country_id' => 55),
		array('name' => "Isla de la Juventud",'country_id' => 55),
		array('name' => "La Habana",'country_id' => 55),
		array('name' => "Las Tunas",'country_id' => 55),
		array('name' => "Matanzas",'country_id' => 55),
		array('name' => "Pinar del Rio",'country_id' => 55),
		array('name' => "Sancti Spiritus",'country_id' => 55),
		array('name' => "Santiago de Cuba",'country_id' => 55),
		array('name' => "Villa Clara",'country_id' => 55),
		array('name' => "Government controlled area",'country_id' => 56),
		array('name' => "Limassol",'country_id' => 56),
		array('name' => "Nicosia District",'country_id' => 56),
		array('name' => "Paphos",'country_id' => 56),
		array('name' => "Turkish controlled area",'country_id' => 56),
		array('name' => "Central Bohemian",'country_id' => 57),
		array('name' => "Frycovice",'country_id' => 57),
		array('name' => "Jihocesky Kraj",'country_id' => 57),
		array('name' => "Jihochesky",'country_id' => 57),
		array('name' => "Jihomoravsky",'country_id' => 57),
		array('name' => "Karlovarsky",'country_id' => 57)
		);
		DB::table('states')->insert($states);

    }
}
